### ISSUE TITLE
Make PR template simpler

### ISSUE THREAD

**Issue by mattwynne** [cucumber/common#1441]
It's often getting ignored, e.g. https://github.com/cucumber/cucumber/pull/1419

We should look at making it simpler, or adding multiple templates for differen types of contribution.

**Comment by mpkorstanje** [comment]
You've picked a bad example. I ignored the template because the PR is still a draft and I haven't gotten around yet to writing up the what and why. I'm using the draft to park it somewhere visible.

That said, it can be much simpler. The checklist at the bottom is the only really important part. For everything else the default github template is good enough (I think cucumber-jvm is using that one).

**Comment by mattwynne** [comment]
Some work here https://github.com/cucumber/common/pull/1621

**Comment by mattwynne** [comment]
🎉 thanks Rien!

**Comment by mpkorstanje** [comment]
??

I didn't fix the PR template. Just the issue ones.

**Comment by mattwynne** [comment]
Ho ho whoops I didn't read your PR carefully enough!
