### ISSUE TITLE
Mixing cucumber and regular expressions

### ISSUE THREAD

**Issue by Polly-Schulze** [cucumber/common#1750]
It is not possible to write a step definition including both a cucumber expression and a regular expression, e.g.
```
  @When("^I buy a book with title ([\\w]+) and author {string}$")
```

Is there a reason why this isn't possible? Are there any plans on making it possible?

**Comment by aslakhellesoy** [comment]
A Regular Expression is a language of its own, with a well-defined grammar. Regular Expressions are parsed with the programming language's Regular Expression parser, which is part of most programming languages' standard library.

A Cucumber Expression is also a language of its own, with a well-defined grammar. Cucumber Expressions are parsed with the [Cucumber Expressions](https://github.com/cucumber/common/tree/main/cucumber-expressions) parser.

> Is there a reason why this isn't possible? 

Yes. The reason is that they are different languages, with different grammars and different parsers. A parser can only parse one language. You cannot mix Java and C# in the same file and expect a parser to parse it. You cannot mix French and Finnish in the same sentence and expect it to make sense. And you cannot mix Cucumber Expressions and Regular Expressions in the same string and expect a parser to understand it.

> Are there any plans on making it possible?

No.
