### ISSUE TITLE
Move or remove `will_be_retried` from `TestStepResult`

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/common#902]
See https://github.com/cucumber/cucumber/commit/4baf62df87f5c946ebecc91f34a411f6101de1ab#r37297905 for context.

Results are only attached to steps, which is why the message was renamed.

I’m not sure where the `will_be_retried` property is written or read, I think somewhere in Cucumber.js @charlierudolph @davidjgoss?

Would it make more sense to place it on `TestCaseFinished`?

**Comment by davidjgoss** [comment]
Agree that `will_be_retried` makes sense on `TestCaseFinished` given it represents a finished attempt.

Cucumber.js currently uses `TestResult` as both a step result and test case attempt result, in [`pickle_runner.ts`](https://github.com/cucumber/cucumber-js/blob/b77bd1d460b79f7cc5d9ca2edf61b207d81587d4/src/runtime/pickle_runner.ts#L48) - in the version of messages we are currently on, `TestCaseFinished` still has a `result`, on which we set the overall duration and status for the attempt. From the [commit](https://github.com/cucumber/cucumber/commit/0c89037cef613465e92448167586ec7f82b151ea) where it was removed, is the idea now to use cucumber-query to resolve that kind of aggregated data rather than emit it on the messages?

**Comment by charlierudolph** [comment]
I'm fine moving it from part of `TestResult` to `TestCaseFinished`. And yes definitely interested how we should be getting a test case attempts results when we don't have a result field on there anymore

**Comment by aslakhellesoy** [comment]
@davidjgoss yes, I think `@cucumber/query` should be used for this. It currently doesn't track `TestCaseStarted#id` / `TestStepFinished#testCaseStartedId`, but it would be trivial to make it do so.

@charlierudolph I'm thinking we could add a `testCaseStartedId` parameter to `#getPickleStepTestStepResults` and `#getPickleTestStepResults`. Then the returned array can be passed through `#getWorstTestStepResult` to get a single result.

WDYT?

**Comment by charlierudolph** [comment]
Sounds good to me.
